### ISSUE TITLE
Error while building trino 367

### ISSUE THREAD

**Issue by brianyye** [prestosql/presto-admin#47]
Download and build trino 367 on Linux version 3.10.0-1160.45.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org), and failed to build "trino-docs".
When I took a look in pom.xml, there is a "docs" but not "trino-docs".
The directory structure also contains a "docs" but not "trino-docs".  I am not
sure if this is the cause.
Error message (copied from typescript file):
```
[[1;34mINFO[m] trino-accumulo-iterators ........................... [1;32mSUCCESS[m [  2.597 s]
[[1;34mINFO[m] trino-accumulo ..................................... [1;32mSUCCESS[m [ 14.008 s]
[[1;34mINFO[m] trino-oracle ....................................... [1;32mSUCCESS[m [  5.893 s]
[[1;34mINFO[m] trino-thrift-api ................................... [1;32mSUCCESS[m [  3.251 s]
[[1;34mINFO[m] trino-thrift-testing-server ........................ [1;32mSUCCESS[m [ 19.717 s]
[[1;34mINFO[m] trino-thrift ....................................... [1;32mSUCCESS[m [  6.099 s]
[[1;34mINFO[m] trino-clickhouse ................................... [1;32mSUCCESS[m [  5.347 s]
[[1;34mINFO[m] trino-atop ......................................... [1;32mSUCCESS[m [  5.163 s]
[[1;34mINFO[m] trino-memsql ....................................... [1;32mSUCCESS[m [  4.998 s]
[[1;34mINFO[m] trino-session-property-managers .................... [1;32mSUCCESS[m [  9.610 s]
[[1;34mINFO[m] trino-raptor-legacy ................................ [1;32mSUCCESS[m [ 25.614 s]
[[1;34mINFO[m] trino-server-main .................................. [1;32mSUCCESS[m [  6.401 s]
[[1;34mINFO[m] trino-resource-group-managers ...................... [1;32mSUCCESS[m [  5.351 s]
[[1;34mINFO[m] trino-mysql ........................................ [1;32mSUCCESS[m [  5.862 s]
[[1;34mINFO[m] trino-mongodb ...................................... [1;32mSUCCESS[m [  5.100 s]
[[1;34mINFO[m] trino-record-decoder ............................... [1;32mSUCCESS[m [  3.035 s]
[[1;34mINFO[m] trino-kinesis ...................................... [1;32mSUCCESS[m [  6.569 s]
[[1;34mINFO[m] trino-iceberg ...................................... [1;32mSUCCESS[m [ 38.895 s]
[[1;34mINFO[m] trino-jmx .......................................... [1;32mSUCCESS[m [  4.972 s]
[[1;34mINFO[m] trino-postgresql ................................... [1;32mSUCCESS[m [  5.387 s]
[[1;34mINFO[m] trino-teradata-functions ........................... [1;32mSUCCESS[m [  2.586 s]
[[1;34mINFO[m] trino-elasticsearch ................................ [1;32mSUCCESS[m [  7.842 s]
[[1;34mINFO[m] trino-ml ........................................... [1;32mSUCCESS[m [  5.018 s]
[[1;34mINFO[m] trino-local-file ................................... [1;32mSUCCESS[m [  3.647 s]
[[1;34mINFO[m] trino-kudu ......................................... [1;32mSUCCESS[m [  5.981 s]
[[1;34mINFO[m] trino-testing-kafka ................................ [1;32mSUCCESS[m [  2.161 s]
[[1;34mINFO[m] trino-pinot ........................................ [1;32mSUCCESS[m [ 17.095 s]
[[1;34mINFO[m] trino-tpcds ........................................ [1;32mSUCCESS[m [  6.633 s]
[[1;34mINFO[m] trino-phoenix ...................................... [1;32mSUCCESS[m [ 20.989 s]
[[1;34mINFO[m] trino-bigquery ..................................... [1;32mSUCCESS[m [  8.470 s]
[[1;34mINFO[m] trino-example-http ................................. [1;32mSUCCESS[m [  3.263 s]
[[1;34mINFO[m] trino-google-sheets ................................ [1;32mSUCCESS[m [  4.191 s]
[[1;34mINFO[m] trino-geospatial ................................... [1;32mSUCCESS[m [ 11.512 s]
[[1;34mINFO[m] trino-prometheus ................................... [1;32mSUCCESS[m [  4.526 s]
[[1;34mINFO[m] trino-cassandra .................................... [1;32mSUCCESS[m [  6.743 s]
[[1;34mINFO[m] trino-sqlserver .................................... [1;32mSUCCESS[m [  4.491 s]
[[1;34mINFO[m] trino-druid ........................................ [1;32mSUCCESS[m [  4.189 s]
[[1;34mINFO[m] trino-kafka ........................................ [1;32mSUCCESS[m [  7.820 s]
[[1;34mINFO[m] trino-redis ........................................ [1;32mSUCCESS[m [  5.980 s]
[[1;34mINFO[m] trino-server ....................................... [1;32mSUCCESS[m [01:14 min]
[[1;34mINFO[m] trino-server-rpm ................................... [1;32mSUCCESS[m [01:07 min]
[[1;34mINFO[m] trino-docs ......................................... [1;31mFAILURE[m [  3.441 s]
[[1;34mINFO[m] trino-proxy ........................................ [1;33mSKIPPED[m
[[1;34mINFO[m] trino-verifier ..................................... [1;33mSKIPPED[m
[[1;34mINFO[m] trino-benchto-benchmarks ........................... [1;33mSKIPPED[m
[[1;34mINFO[m] trino-product-tests ................................ [1;33mSKIPPED[m
[[1;34mINFO[m] trino-product-tests-launcher ....................... [1;33mSKIPPED[m
[[1;34mINFO[m] trino-server-dev ................................... [1;33mSKIPPED[m
[[1;34mINFO[m] trino-test-jdbc-compatibility-old-driver ........... [1;33mSKIPPED[m
[[1;34mINFO[m] trino-test-jdbc-compatibility-old-server ........... [1;33mSKIPPED[m
[[1;34mINFO[m] trino-tests ........................................ [1;33mSKIPPED[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  14:16 min
[[1;34mINFO[m] Finished at: 2022-01-03T10:53:41-06:00
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32morg.codehaus.mojo:exec-maven-plugin:1.6.0:exec[m [1m(run-sphinx)[m on project [36mtrino-docs[m: [1;31mCommand execution failed.[m: Process exited with an error: 125 (Exit value: 125) -> [1m[Help 1][m
[1;31morg.apache.maven.lifecycle.LifecycleExecutionException[m: [1;31mFailed to execute goal [32morg.codehaus.mojo:exec-maven-plugin:1.6.0:exec[m [1m(run-sphinx)[m on project [36mtrino-docs[m: [1;31mCommand execution failed.[m[m
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:215[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:972[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:293[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:196[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.apache.maven.wrapper.BootstrapMainStarter.start ([1mBootstrapMainStarter.java:39[m)
    [1mat[m org.apache.maven.wrapper.WrapperExecutor.execute ([1mWrapperExecutor.java:122[m)
    [1mat[m org.apache.maven.wrapper.MavenWrapperMain.main ([1mMavenWrapperMain.java:61[m)
[1mCaused by[m: org.apache.maven.plugin.MojoExecutionException: [1;31mCommand execution failed.[m
    [1mat[m org.codehaus.mojo.exec.ExecMojo.execute ([1mExecMojo.java:326[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:137[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:210[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:972[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:293[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:196[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.apache.maven.wrapper.BootstrapMainStarter.start ([1mBootstrapMainStarter.java:39[m)
    [1mat[m org.apache.maven.wrapper.WrapperExecutor.execute ([1mWrapperExecutor.java:122[m)
    [1mat[m org.apache.maven.wrapper.MavenWrapperMain.main ([1mMavenWrapperMain.java:61[m)
```

**Comment by ebyhr** [comment]
Please read README. 
> Trino-admin (formerly known as presto-admin) is deprecated and will not work with new versions of Trino (>350)

`docs` module requires docker. Could you make sure the requirement?

**Comment by brianyye** [comment]
Hi Trinodb/Trino-Admin,

Yes, I do have docker installed:
the command:
    docker -v
returns:
    Docker version 20.10.11, build dea9396

Also for your information, PrestoSql 337 has a directory named
"presto-docs", but trino only has the directory "docs", no "trino-docs".

Thanks,
Brian Ye

**Comment by ebyhr** [comment]
What command did you execute?

**Comment by brianyye** [comment]
I just followed the instructions in README.md and issue:

./mvnw clean install -DskipTests

Thanks,
Brian Ye

**Comment by ebyhr** [comment]
How about the result of `/mvnw -v`? Also, please share the entire log of `./mvnw clean install -DskipTests -pl docs`.

**Comment by brianyye** [comment]
Hi,

Here is the output:

 ./mvnw -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home:
/home/briany/.m2/wrapper/dists/apache-maven-3.8.4-bin/5sjqtqkfjmakil1qhdtgrnjjdc/apache-maven-3.8.4
Java version: 11.0.13, vendor: Red Hat, Inc., runtime:
/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.45.1.el7.x86_64", arch: "amd64",
family: "unix"



build output:
Script started on Wed 05 Jan 2022 10:26:49 AM CST
***@***.***:~/PreAlpha/ThirdParty/trino/master
***@***.*** master]$ ./mvnw clean install -DskipTests -pl docs
[ [1;34mINFO [m] Scanning for projects...
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m------------------------< [0;36mio.trino:trino-docs
[0;1m >------------------------- [m
[ [1;34mINFO [m] [1mBuilding trino-docs 367-SNAPSHOT [m
[ [1;34mINFO [m] [1m--------------------------------[ pom
]--------------------------------- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-clean-plugin:3.0.0:clean [m
[1m(default-clean) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] Deleting
/home/briany/PreAlpha/ThirdParty/trino/master/docs/target
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mdrift-maven-plugin:1.14:generate-thrift-idl
[m [1m(default) [m @ [36mtrino-docs [0;1m --- [m
Downloading from sonatype-nexus-snapshots:
https://oss.sonatype.org/content/repositories/snapshots/io/trino/trino-thrift-api/367-SNAPSHOT/maven-metadata.xml
Downloading from sonatype-nexus-snapshots:
https://oss.sonatype.org/content/repositories/snapshots/io/trino/trino-root/367-SNAPSHOT/maven-metadata.xml
Downloading from sonatype-nexus-snapshots:
https://oss.sonatype.org/content/repositories/snapshots/io/trino/trino-spi/367-SNAPSHOT/maven-metadata.xml
[ [1;34mINFO [m] Found Thrift service: TrinoThriftService
[ [1;34mINFO [m] Wrote Thrift IDL to
/home/briany/PreAlpha/ThirdParty/trino/master/docs/target/TrinoThriftService.thrift
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mexec-maven-plugin:1.6.0:java [m
[1m(validate-reserved) [m @ [36mtrino-docs [0;1m --- [m
Downloading from sonatype-nexus-snapshots:
https://oss.sonatype.org/content/repositories/snapshots/io/trino/trino-parser/367-SNAPSHOT/maven-metadata.xml
Downloading from maven-default-http-blocker:
http://0.0.0.0/io/trino/trino-parser/367-SNAPSHOT/maven-metadata.xml
[ [1;33mWARNING [m] Could not transfer metadata
io.trino:trino-parser:367-SNAPSHOT/maven-metadata.xml from/to
maven-default-http-blocker (http://0.0.0.0/): transfer failed for
http://0.0.0.0/io/trino/trino-parser/367-SNAPSHOT/maven-metadata.xml
[ [1;33mWARNING [m] Failure to transfer
io.trino:trino-parser:367-SNAPSHOT/maven-metadata.xml from http://0.0.0.0/
was cached in the local repository, resolution will not be reattempted
until the update interval of maven-default-http-blocker has elapsed or
updates are forced. Original error: Could not transfer metadata
io.trino:trino-parser:367-SNAPSHOT/maven-metadata.xml from/to
maven-default-http-blocker (http://0.0.0.0/): transfer failed for
http://0.0.0.0/io/trino/trino-parser/367-SNAPSHOT/maven-metadata.xml
Validating
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/language/reserved.rst
Validated 75 reserved identifiers
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mexec-maven-plugin:1.6.0:exec [m
[1m(validate-thrift-idl) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-enforcer-plugin:3.0.0-M3:enforce [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mdependency-scope-maven-plugin:0.10:check [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] No test dependency scope issues found
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mlicense-maven-plugin:3.0:check [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] Checking licenses...
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/no-inequality-pushdown-text-type.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/alter-table-limitation.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/no-pushdown-text-type.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/sql-delete-limitation.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/jdbc-case-insensitive-matching.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/non-transactional-insert.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/security/kerberos-configuration.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/security/kerberos-services.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/security/ktadd-note.fragment
[ [1;33mWARNING [m] Unknown file extension:
/home/briany/PreAlpha/ThirdParty/trino/master/docs/src/main/sphinx/connector/jdbc-type-mapping.fragment
[ [1;33mWARNING [m] Unable to find a comment style definition for some
files. You may want to add a custom mapping for the relevant file
extensions.
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-checkstyle-plugin:3.1.2:check [m
[1m(checkstyle) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] You have 0 Checkstyle violations.
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mjacoco-maven-plugin:0.8.6:prepare-agent [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;33mWARNING [m] The artifact xml-apis:xml-apis:jar:2.0.2 has been
relocated to xml-apis:xml-apis:jar:1.0.b2
[ [1;34mINFO [m] Skipping JaCoCo execution because property jacoco.skip is
set.
[ [1;34mINFO [m] argLine set to empty
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mgit-commit-id-plugin:4.0.3:revision [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-dependency-plugin:3.1.2:analyze-only [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] Skipping pom project
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m---
[0;32mmaven-dependency-plugin:3.1.2:analyze-duplicate [m [1m(default) [m @
[36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] No duplicate dependencies found in <dependencies/> or in
<dependencyManagement/>
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mduplicate-finder-maven-plugin:1.5.0:check [m
[1m(default) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] Ignoring POM project!
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmodernizer-maven-plugin:2.2.0:modernizer [m
[1m(modernizer) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mjacoco-maven-plugin:0.8.6:report [m
[1m(report) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] Skipping JaCoCo execution because property jacoco.skip is
set.
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-jar-plugin:3.2.0:test-jar [m
[1m(attach-tests) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m] Skipping packaging of the test-jar
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-source-plugin:3.2.0:jar-no-fork [m
[1m(attach-sources) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mmaven-source-plugin:3.2.0:test-jar-no-fork [m
[1m(attach-sources) [m @ [36mtrino-docs [0;1m --- [m
[ [1;34mINFO [m]
[ [1;34mINFO [m] [1m--- [0;32mexec-maven-plugin:1.6.0:exec [m
[1m(run-sphinx) [m @ [36mtrino-docs [0;1m --- [m
+ cd /home/briany/PreAlpha/ThirdParty/trino/master/docs
+ test -t 1
+ OPTS=
+ SPHINX_IMAGE=ghcr.io/trinodb/build/sphinx:3
++ id -u
++ id -g
+ docker run --rm -e TRINO_VERSION -u 518804226:518800513 -v
/home/briany/PreAlpha/ThirdParty/trino/master/docs:/docs
ghcr.io/trinodb/build/sphinx:3 sphinx-build -j auto -b html -W -d
target/doctrees src/main/sphinx target/html
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock.
Is the docker daemon running?.
See 'docker run --help'.
[ [1;31mERROR [m] Command execution failed.
[1;31morg.apache.commons.exec.ExecuteException [m: [1;31mProcess exited
with an error: 125 (Exit value: 125) [m
    [1mat [m org.apache.commons.exec.DefaultExecutor.executeInternal (
[1mDefaultExecutor.java:404 [m)
    [1mat [m org.apache.commons.exec.DefaultExecutor.execute (
[1mDefaultExecutor.java:166 [m)
    [1mat [m org.codehaus.mojo.exec.ExecMojo.executeCommandLine (
[1mExecMojo.java:804 [m)
    [1mat [m org.codehaus.mojo.exec.ExecMojo.executeCommandLine (
[1mExecMojo.java:751 [m)
    [1mat [m org.codehaus.mojo.exec.ExecMojo.execute ( [1mExecMojo.java:313
[m)
    [1mat [m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo
( [1mDefaultBuildPluginManager.java:137 [m)
    [1mat [m org.apache.maven.lifecycle.internal.MojoExecutor.execute (
[1mMojoExecutor.java:210 [m)
    [1mat [m org.apache.maven.lifecycle.internal.MojoExecutor.execute (
[1mMojoExecutor.java:156 [m)
    [1mat [m org.apache.maven.lifecycle.internal.MojoExecutor.execute (
[1mMojoExecutor.java:148 [m)
    [1mat [m
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
[1mLifecycleModuleBuilder.java:117 [m)
    [1mat [m
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
[1mLifecycleModuleBuilder.java:81 [m)
    [1mat [m
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
( [1mSingleThreadedBuilder.java:56 [m)
    [1mat [m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (
[1mLifecycleStarter.java:128 [m)
    [1mat [m org.apache.maven.DefaultMaven.doExecute (
[1mDefaultMaven.java:305 [m)
    [1mat [m org.apache.maven.DefaultMaven.doExecute (
[1mDefaultMaven.java:192 [m)
    [1mat [m org.apache.maven.DefaultMaven.execute (
[1mDefaultMaven.java:105 [m)
    [1mat [m org.apache.maven.cli.MavenCli.execute ( [1mMavenCli.java:972
[m)
    [1mat [m org.apache.maven.cli.MavenCli.doMain ( [1mMavenCli.java:293 [m)
    [1mat [m org.apache.maven.cli.MavenCli.main ( [1mMavenCli.java:196 [m)
    [1mat [m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (
[1mNative Method [m)
    [1mat [m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (
[1mNativeMethodAccessorImpl.java:62 [m)
    [1mat [m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (
[1mDelegatingMethodAccessorImpl.java:43 [m)
    [1mat [m java.lang.reflect.Method.invoke ( [1mMethod.java:566 [m)
    [1mat [m
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (
[1mLauncher.java:282 [m)
    [1mat [m org.codehaus.plexus.classworlds.launcher.Launcher.launch (
[1mLauncher.java:225 [m)
    [1mat [m
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (
[1mLauncher.java:406 [m)
    [1mat [m org.codehaus.plexus.classworlds.launcher.Launcher.main (
[1mLauncher.java:347 [m)
    [1mat [m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (
[1mNative Method [m)
    [1mat [m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (
[1mNativeMethodAccessorImpl.java:62 [m)
    [1mat [m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (
[1mDelegatingMethodAccessorImpl.java:43 [m)
    [1mat [m java.lang.reflect.Method.invoke ( [1mMethod.java:566 [m)
    [1mat [m org.apache.maven.wrapper.BootstrapMainStarter.start (
[1mBootstrapMainStarter.java:39 [m)
    [1mat [m org.apache.maven.wrapper.WrapperExecutor.execute (
[1mWrapperExecutor.java:122 [m)
    [1mat [m org.apache.maven.wrapper.MavenWrapperMain.main (
[1mMavenWrapperMain.java:61 [m)
[ [1;34mINFO [m]
[1m------------------------------------------------------------------------
[m
[ [1;34mINFO [m] [1;31mBUILD FAILURE [m
[ [1;34mINFO [m]
[1m------------------------------------------------------------------------
[m
[ [1;34mINFO [m] Total time:  27.360 s
[ [1;34mINFO [m] Finished at: 2022-01-05T10:27:27-06:00
[ [1;34mINFO [m]
[1m------------------------------------------------------------------------
[m
[ [1;31mERROR [m] Failed to execute goal
[32morg.codehaus.mojo:exec-maven-plugin:1.6.0:exec [m [1m(run-sphinx) [m on
project [36mtrino-docs [m: [1;31mCommand execution failed. [m: Process
exited with an error: 125 (Exit value: 125) -> [1m[Help 1] [m
[ [1;31mERROR [m]
[ [1;31mERROR [m] To see the full stack trace of the errors, re-run Maven
with the [1m-e [m switch.
[ [1;31mERROR [m] Re-run Maven using the [1m-X [m switch to enable full
debug logging.
[ [1;31mERROR [m]
[ [1;31mERROR [m] For more information about the errors and possible
solutions, please read the following articles:
[ [1;31mERROR [m] [1m[Help 1] [m
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[0m [0m ***@***.***:~/PreAlpha/ThirdParty/trino/master
***@***.*** master]$ exit

Script done on Wed 05 Jan 2022 10:27:31 AM CST

Thanks,
Brian Ye

**Comment by ebyhr** [comment]
> docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

Please see the error message. As I already mentioned before, docs module requires docker. You can skip by `!:trino-docs` if you don't want to build docs module.

**Comment by brianyye** [comment]
Thanks.
I suggest that you add the following to the instructions:
1. docker daemon be running
2. /var/run/docker.sock be readable by the account building the project.
Best regards,
Brian Ye
